#!/bin/bash

set -TEeuo pipefail

readonly BASE_DIR="$(dirname -- "$(readlink -e -- "$0")")"

readonly BRANCH="$(git rev-parse --abbrev-ref HEAD)"
readonly TAG="$(git describe --tags || printf '-')"

cd "$BASE_DIR/src"
zip -r ../"untrack-urls-webext.$BRANCH.$TAG.zip" manifest.json .
