#!/bin/bash

set -Eeuo pipefail

BASE_DIR="$(readlink --canonicalize-existing -- "$0")"
BASE_DIR="$(dirname -- "$BASE_DIR")"
declare -r BASE_DIR

npx web-ext build --source-dir="$BASE_DIR/src" --overwrite-dest --artifacts-dir="$BASE_DIR/out"
