#!/bin/bash

set -TEeuo pipefail

readonly BASE_DIR="$(dirname -- "$(readlink -e -- "$0")")"

web-ext run --verbose --firefox="$FIREFOX" --devtools --source-dir="$BASE_DIR/src" --artifacts-dir="$BASE_DIR/out"
