#!/bin/bash

set -TEeuo pipefail

readonly BASE_DIR="$(dirname -- $(readlink -e -- "$0"))"

readonly PROVIDER="${PROVIDER:-google}"

case "$PROVIDER" in
'duckduckgo')
	download_favicon() {
		local -r DOMAIN="${1?no domain}"
		local -r FAVICON_FILE="${2?no favicon file}"
		curl --location --silent "https://external-content.duckduckgo.com/ip3/$DOMAIN.ico" \
			> "$FAVICON_FILE"~
		convert "$FAVICON_FILE"~ -resize 16x16 "$FAVICON_FILE"
		rm "$FAVICON_FILE"~
	}
	;;
'google')
	download_favicon() {
		local -r DOMAIN="${1?no domain}"
		local -r FAVICON_FILE="${2?no favicon file}"
		curl --location --silent "https://www.google.com/s2/favicons?domain=$DOMAIN&sz=16" \
			> "$FAVICON_FILE"
	}
	;;
*)
	echo "$0: fatal: unrecognized provider: $PROVIDER" >&2
	exit 1
	;;
esac

echo "$0: favicon provider: $PROVIDER" >&2

for FAVICON_FILE; do
	DOMAIN="${FAVICON_FILE%.*}"
	printf '%s\n' "$DOMAIN"
	download_favicon "$DOMAIN" "$FAVICON_FILE"
	MIME_TYPE="$(file --brief --mime-type "$FAVICON_FILE")"
	TARGET_FILE=
	case "$MIME_TYPE" in
	'image/jpeg')
		echo "$0: warn: $DOMAIN provided a JPEG favicon" >&2
		mogrify -strip "$FAVICON_FILE"
		TARGET_FILE="$BASE_DIR/$DOMAIN.jpg"
		;;
	'image/png')
		mogrify -strip "$FAVICON_FILE"
		TARGET_FILE="$BASE_DIR/$DOMAIN.png"
		;;
	*)
		echo "$0: warn: unrecognized MIME-type $MIME_TYPE for $FAVICON_FILE" >&2
		continue
		;;
	esac
	if [[ ! "$FAVICON_FILE" -ef "$TARGET_FILE" ]]; then
		mv "$FAVICON_FILE" "$TARGET_FILE"
	fi
done
