#!/bin/bash

set -TEeuo pipefail

readonly BASE_DIR="$(dirname -- $(readlink -e -- "$0"))"

readonly PROVIDER="${PROVIDER:-google}"

EXIT_CODE=0

case "$PROVIDER" in
'duckduckgo')
	download_favicon() {
		local -r DOMAIN="${1?no domain}"
		local -r FAVICON_FILE="${2?no favicon file}"
		curl --location --silent "https://external-content.duckduckgo.com/ip3/$DOMAIN.ico" \
			> "$FAVICON_FILE"~
		convert "$FAVICON_FILE"~ -resize 16x16 "$FAVICON_FILE"
		rm "$FAVICON_FILE"~
	}
	;;
'google')
	download_favicon() {
		local -r DOMAIN="${1?no domain}"
		local -r FAVICON_FILE="${2?no favicon file}"
		curl --location --silent "https://www.google.com/s2/favicons?domain=$DOMAIN&sz=16" \
			> "$FAVICON_FILE"
	}
	;;
*)
	echo "$0: fatal: unrecognized provider: $PROVIDER" >&2
	exit 1
	;;
esac

printf '%s: favicon provider: %s\n' "$0" "$PROVIDER"

for FAVICON_FILE; do
	DOMAIN="${FAVICON_FILE%.*}"
	printf '%s\n' "$DOMAIN"
	FAVICON_FILE="$FAVICON_FILE~"
	download_favicon "$DOMAIN" "$FAVICON_FILE"
	MIME_TYPE="$(file --brief --mime-type "$FAVICON_FILE")"
	TARGET_FILE=
	if [[ "$MIME_TYPE" == 'image/'* ]]; then
		mogrify -strip "$FAVICON_FILE"
	fi
	case "$MIME_TYPE" in
	'image/jpeg')
		echo "$0: warn: $DOMAIN provided a JPEG favicon" >&2
		;;
	'image/png')
		;;
	'image/webp')
		continue
		;;
	*)
		echo "$0: warn: unrecognized MIME-type $MIME_TYPE for $FAVICON_FILE" >&2
		EXIT_CODE=1
		continue
		;;
	esac
	TARGET_FILE="$BASE_DIR/$DOMAIN.webp"
	cwebp -lossless -z 9 "$FAVICON_FILE" -o "$TARGET_FILE"
	rm -vrf "$FAVICON_FILE"
done

exit "$EXIT_CODE"
