#!/bin/bash

set -TEeuo pipefail

declare -r PROVIDER="${PROVIDER:-google}"

declare -i EXIT_CODE=0

case "$PROVIDER" in
'duckduckgo'|'ddg')
	download_favicon() {
		local -r DOMAIN="${1?no domain}"
		local -r FAVICON_FILE="${2?no favicon file}"
		curl --location --silent -- "https://external-content.duckduckgo.com/ip3/$DOMAIN.ico" \
			> "$FAVICON_FILE"
	}
	;;
'google')
	download_favicon() {
		local -r DOMAIN="${1?no domain}"
		local -r FAVICON_FILE="${2?no favicon file}"
		curl --location --silent -- "https://www.google.com/s2/favicons?domain=$DOMAIN&sz=16" \
			> "$FAVICON_FILE"
	}
	;;
*)
	echo "$0: fatal: unrecognized favicon provider: $PROVIDER" >&2
	exit 1
	;;
esac

echo "$0: info: favicon provider: $PROVIDER" >&2

while read -r DOMAIN; do
	printf '%s\n' "$DOMAIN"
	TMP_FAVICON_FILE="$DOMAIN~"
	download_favicon "$DOMAIN" "$TMP_FAVICON_FILE"
	MIME_TYPE="$(file --brief --mime-type "$TMP_FAVICON_FILE")"
	case "$MIME_TYPE" in
	'image/jpeg')
		echo "$0: warn: $DOMAIN provided a JPEG favicon" >&2
		cwebp -quiet -lossless -z 9 -resize 16 16 "$TMP_FAVICON_FILE" -o "$DOMAIN.webp"
		;;
	'image/png'|'image/webp')
		cwebp -quiet -lossless -z 9 -resize 16 16 "$TMP_FAVICON_FILE" -o "$DOMAIN.webp"
		;;
	*)
		echo "$0: error: unrecognized MIME-type $MIME_TYPE for $TMP_FAVICON_FILE" >&2
		EXIT_CODE=1
		;;
	esac
	rm -f -- "$TMP_FAVICON_FILE"
done

exit $EXIT_CODE
